In [1]:
# importing pandas library
import pandas as pd

## EDA

In [2]:
#Combine Jan to Dec CSV file
import glob

# Path to your folder (adjust this)
folder_path = r"C:\Users\konta\Downloads\Bike\Folder"

all_files = glob.glob(folder_path + "/*.csv")

print(all_files)

['C:\\Users\\konta\\Downloads\\Bike\\Folder\\202501-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202502-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202503-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202504-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202505-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202506-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202507-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202508-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202509-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202510-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202511-divvy-tripdata.csv', 'C:\\Users\\konta\\Downloads\\Bike\\Folder\\202512-divvy-tripdata.csv']

In [3]:
# Create a DataFrame
df_list = [pd.read_csv(file) for file in all_files]
df = pd.concat(df_list, ignore_index=True)

In [4]:
df.shape

(5552994, 13)

In [5]:
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,23:54.5,37:52.0,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,44:06.8,49:11.1,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,16:27.7,28:03.2,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,49:05.8,52:40.0,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,38:32.3,41:06.8,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5552994 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), str(9)
memory usage: 550.8 MB

In [7]:
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1243305
end_station_id        1243305
start_lat                   0
start_lng                   0
end_lat                  5535
end_lng                  5535
member_casual               0
dtype: int64

##### Treating Null Value

In [8]:
# Since,end_lat and end_lang has just 5535 null values in 5.5 million rows , it would be better to drop these rows having null
df=df.dropna(subset=['end_lat','end_lng'])

In [9]:
#now check
df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1184673
start_station_id      1184673
end_station_name      1237770
end_station_id        1237770
start_lat                   0
start_lng                   0
end_lat                     0
end_lng                     0
member_casual               0
dtype: int64

In [10]:
#start_station_name, start_station_id,end_station_name and end_sation_id have more than 1 million null values 
# this numbers are significient ,it would be better to replace with 'unknown'.
df['start_station_name']=df['start_station_name'].fillna('unknown')
df['start_station_id']=df['start_station_id'].fillna('unknown')
df['end_station_name']=df['end_station_name'].fillna('unknown')
df['end_station_id']=df['end_station_id'].fillna('unknown')

In [11]:
df.isnull().sum()

ride_id               0
rideable_type         0
started_at            0
ended_at              0
start_station_name    0
start_station_id      0
end_station_name      0
end_station_id        0
start_lat             0
start_lng             0
end_lat               0
end_lng               0
member_casual         0
dtype: int64

In [12]:
df.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7569BC890583FCD7,classic_bike,2025-01-21 17:23:54.538,2025-01-21 17:37:52.015,Wacker Dr & Washington St,KA1503000072,McClurg Ct & Ohio St,TA1306000029,41.883143,-87.637242,41.892592,-87.617289,member
1,013609308856B7FC,electric_bike,2025-01-11 15:44:06.795,2025-01-11 15:49:11.139,Halsted St & Wrightwood Ave,TA1309000061,Racine Ave & Belmont Ave,TA1308000019,41.929147,-87.649153,41.939743,-87.658865,member
2,EACACD3CE0607C0D,classic_bike,2025-01-02 15:16:27.730,2025-01-02 15:28:03.230,Southport Ave & Waveland Ave,13235,Broadway & Cornelia Ave,13278,41.948226,-87.664071,41.945529,-87.646439,member
3,EAA2485BA64710D3,classic_bike,2025-01-23 08:49:05.814,2025-01-23 08:52:40.047,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member
4,7F8BE2471C7F746B,electric_bike,2025-01-16 08:38:32.338,2025-01-16 08:41:06.767,Southport Ave & Waveland Ave,13235,Southport Ave & Roscoe St,13071,41.948226,-87.664071,41.943739,-87.664020,member

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 5547459 entries, 0 to 5552993
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), str(9)
memory usage: 592.5 MB

In [14]:
# As started_at and ended_at in string datatype ,have to change into date time formate
# Convert to datetime
df['started_at'] = pd.to_datetime(df['started_at']) # pd.to_datetime(df['started_at'],formate='%d-%m-%Y %H:%M:%S'
df['ended_at']   = pd.to_datetime(df['ended_at'])

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
import sqlalchemy
import pyodbc
server = r"KARAN\SQLEXPRESS"   # your SQL Server instance name
database = "data_analysis_bike"  # replace with your DB name
driver = "ODBC Driver 17 for SQL Server"

# Connection string using Windows Authentication
connection_string = f"mssql+pyodbc://@{server}/{database}?driver={driver}"

# Create engine
engine = sqlalchemy.create_engine(connection_string)
print("done")

In [ ]:
table_name="ride_details"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print("Successfully loaded into table")